/*
Slurm REST API

API to access and control Slurm

API version: Slurm-24.05.3&openapi/slurmdbd&openapi/slurmctld
Contact: sales@schedmd.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the SlurmdbV0041DeleteSingleQos200ResponseMetaClient type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SlurmdbV0041DeleteSingleQos200ResponseMetaClient{}

// SlurmdbV0041DeleteSingleQos200ResponseMetaClient struct for SlurmdbV0041DeleteSingleQos200ResponseMetaClient
type SlurmdbV0041DeleteSingleQos200ResponseMetaClient struct {
	// Client source description
	Source *string `json:"source,omitempty"`
	// Client user (if known)
	User *string `json:"user,omitempty"`
	// Client group (if known)
	Group *string `json:"group,omitempty"`
}

// NewSlurmdbV0041DeleteSingleQos200ResponseMetaClient instantiates a new SlurmdbV0041DeleteSingleQos200ResponseMetaClient object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSlurmdbV0041DeleteSingleQos200ResponseMetaClient() *SlurmdbV0041DeleteSingleQos200ResponseMetaClient {
	this := SlurmdbV0041DeleteSingleQos200ResponseMetaClient{}
	return &this
}

// NewSlurmdbV0041DeleteSingleQos200ResponseMetaClientWithDefaults instantiates a new SlurmdbV0041DeleteSingleQos200ResponseMetaClient object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSlurmdbV0041DeleteSingleQos200ResponseMetaClientWithDefaults() *SlurmdbV0041DeleteSingleQos200ResponseMetaClient {
	this := SlurmdbV0041DeleteSingleQos200ResponseMetaClient{}
	return &this
}

// GetSource returns the Source field value if set, zero value otherwise.
func (o *SlurmdbV0041DeleteSingleQos200ResponseMetaClient) GetSource() string {
	if o == nil || IsNil(o.Source) {
		var ret string
		return ret
	}
	return *o.Source
}

// GetSourceOk returns a tuple with the Source field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SlurmdbV0041DeleteSingleQos200ResponseMetaClient) GetSourceOk() (*string, bool) {
	if o == nil || IsNil(o.Source) {
		return nil, false
	}
	return o.Source, true
}

// HasSource returns a boolean if a field has been set.
func (o *SlurmdbV0041DeleteSingleQos200ResponseMetaClient) HasSource() bool {
	if o != nil && !IsNil(o.Source) {
		return true
	}

	return false
}

// SetSource gets a reference to the given string and assigns it to the Source field.
func (o *SlurmdbV0041DeleteSingleQos200ResponseMetaClient) SetSource(v string) {
	o.Source = &v
}

// GetUser returns the User field value if set, zero value otherwise.
func (o *SlurmdbV0041DeleteSingleQos200ResponseMetaClient) GetUser() string {
	if o == nil || IsNil(o.User) {
		var ret string
		return ret
	}
	return *o.User
}

// GetUserOk returns a tuple with the User field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SlurmdbV0041DeleteSingleQos200ResponseMetaClient) GetUserOk() (*string, bool) {
	if o == nil || IsNil(o.User) {
		return nil, false
	}
	return o.User, true
}

// HasUser returns a boolean if a field has been set.
func (o *SlurmdbV0041DeleteSingleQos200ResponseMetaClient) HasUser() bool {
	if o != nil && !IsNil(o.User) {
		return true
	}

	return false
}

// SetUser gets a reference to the given string and assigns it to the User field.
func (o *SlurmdbV0041DeleteSingleQos200ResponseMetaClient) SetUser(v string) {
	o.User = &v
}

// GetGroup returns the Group field value if set, zero value otherwise.
func (o *SlurmdbV0041DeleteSingleQos200ResponseMetaClient) GetGroup() string {
	if o == nil || IsNil(o.Group) {
		var ret string
		return ret
	}
	return *o.Group
}

// GetGroupOk returns a tuple with the Group field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SlurmdbV0041DeleteSingleQos200ResponseMetaClient) GetGroupOk() (*string, bool) {
	if o == nil || IsNil(o.Group) {
		return nil, false
	}
	return o.Group, true
}

// HasGroup returns a boolean if a field has been set.
func (o *SlurmdbV0041DeleteSingleQos200ResponseMetaClient) HasGroup() bool {
	if o != nil && !IsNil(o.Group) {
		return true
	}

	return false
}

// SetGroup gets a reference to the given string and assigns it to the Group field.
func (o *SlurmdbV0041DeleteSingleQos200ResponseMetaClient) SetGroup(v string) {
	o.Group = &v
}

func (o SlurmdbV0041DeleteSingleQos200ResponseMetaClient) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SlurmdbV0041DeleteSingleQos200ResponseMetaClient) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Source) {
		toSerialize["source"] = o.Source
	}
	if !IsNil(o.User) {
		toSerialize["user"] = o.User
	}
	if !IsNil(o.Group) {
		toSerialize["group"] = o.Group
	}
	return toSerialize, nil
}

type NullableSlurmdbV0041DeleteSingleQos200ResponseMetaClient struct {
	value *SlurmdbV0041DeleteSingleQos200ResponseMetaClient
	isSet bool
}

func (v NullableSlurmdbV0041DeleteSingleQos200ResponseMetaClient) Get() *SlurmdbV0041DeleteSingleQos200ResponseMetaClient {
	return v.value
}

func (v *NullableSlurmdbV0041DeleteSingleQos200ResponseMetaClient) Set(val *SlurmdbV0041DeleteSingleQos200ResponseMetaClient) {
	v.value = val
	v.isSet = true
}

func (v NullableSlurmdbV0041DeleteSingleQos200ResponseMetaClient) IsSet() bool {
	return v.isSet
}

func (v *NullableSlurmdbV0041DeleteSingleQos200ResponseMetaClient) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSlurmdbV0041DeleteSingleQos200ResponseMetaClient(val *SlurmdbV0041DeleteSingleQos200ResponseMetaClient) *NullableSlurmdbV0041DeleteSingleQos200ResponseMetaClient {
	return &NullableSlurmdbV0041DeleteSingleQos200ResponseMetaClient{value: val, isSet: true}
}

func (v NullableSlurmdbV0041DeleteSingleQos200ResponseMetaClient) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSlurmdbV0041DeleteSingleQos200ResponseMetaClient) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


