/*
Slurm REST API

API to access and control Slurm

API version: Slurm-24.05.3&openapi/slurmdbd&openapi/slurmctld
Contact: sales@schedmd.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the SlurmdbV0041DeleteSingleQos200ResponseErrorsInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SlurmdbV0041DeleteSingleQos200ResponseErrorsInner{}

// SlurmdbV0041DeleteSingleQos200ResponseErrorsInner struct for SlurmdbV0041DeleteSingleQos200ResponseErrorsInner
type SlurmdbV0041DeleteSingleQos200ResponseErrorsInner struct {
	// Long form error description
	Description *string `json:"description,omitempty"`
	// Slurm numeric error identifier
	ErrorNumber *int32 `json:"error_number,omitempty"`
	// Short form error description
	Error *string `json:"error,omitempty"`
	// Source of error or where error was first detected
	Source *string `json:"source,omitempty"`
}

// NewSlurmdbV0041DeleteSingleQos200ResponseErrorsInner instantiates a new SlurmdbV0041DeleteSingleQos200ResponseErrorsInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSlurmdbV0041DeleteSingleQos200ResponseErrorsInner() *SlurmdbV0041DeleteSingleQos200ResponseErrorsInner {
	this := SlurmdbV0041DeleteSingleQos200ResponseErrorsInner{}
	return &this
}

// NewSlurmdbV0041DeleteSingleQos200ResponseErrorsInnerWithDefaults instantiates a new SlurmdbV0041DeleteSingleQos200ResponseErrorsInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSlurmdbV0041DeleteSingleQos200ResponseErrorsInnerWithDefaults() *SlurmdbV0041DeleteSingleQos200ResponseErrorsInner {
	this := SlurmdbV0041DeleteSingleQos200ResponseErrorsInner{}
	return &this
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *SlurmdbV0041DeleteSingleQos200ResponseErrorsInner) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SlurmdbV0041DeleteSingleQos200ResponseErrorsInner) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *SlurmdbV0041DeleteSingleQos200ResponseErrorsInner) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *SlurmdbV0041DeleteSingleQos200ResponseErrorsInner) SetDescription(v string) {
	o.Description = &v
}

// GetErrorNumber returns the ErrorNumber field value if set, zero value otherwise.
func (o *SlurmdbV0041DeleteSingleQos200ResponseErrorsInner) GetErrorNumber() int32 {
	if o == nil || IsNil(o.ErrorNumber) {
		var ret int32
		return ret
	}
	return *o.ErrorNumber
}

// GetErrorNumberOk returns a tuple with the ErrorNumber field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SlurmdbV0041DeleteSingleQos200ResponseErrorsInner) GetErrorNumberOk() (*int32, bool) {
	if o == nil || IsNil(o.ErrorNumber) {
		return nil, false
	}
	return o.ErrorNumber, true
}

// HasErrorNumber returns a boolean if a field has been set.
func (o *SlurmdbV0041DeleteSingleQos200ResponseErrorsInner) HasErrorNumber() bool {
	if o != nil && !IsNil(o.ErrorNumber) {
		return true
	}

	return false
}

// SetErrorNumber gets a reference to the given int32 and assigns it to the ErrorNumber field.
func (o *SlurmdbV0041DeleteSingleQos200ResponseErrorsInner) SetErrorNumber(v int32) {
	o.ErrorNumber = &v
}

// GetError returns the Error field value if set, zero value otherwise.
func (o *SlurmdbV0041DeleteSingleQos200ResponseErrorsInner) GetError() string {
	if o == nil || IsNil(o.Error) {
		var ret string
		return ret
	}
	return *o.Error
}

// GetErrorOk returns a tuple with the Error field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SlurmdbV0041DeleteSingleQos200ResponseErrorsInner) GetErrorOk() (*string, bool) {
	if o == nil || IsNil(o.Error) {
		return nil, false
	}
	return o.Error, true
}

// HasError returns a boolean if a field has been set.
func (o *SlurmdbV0041DeleteSingleQos200ResponseErrorsInner) HasError() bool {
	if o != nil && !IsNil(o.Error) {
		return true
	}

	return false
}

// SetError gets a reference to the given string and assigns it to the Error field.
func (o *SlurmdbV0041DeleteSingleQos200ResponseErrorsInner) SetError(v string) {
	o.Error = &v
}

// GetSource returns the Source field value if set, zero value otherwise.
func (o *SlurmdbV0041DeleteSingleQos200ResponseErrorsInner) GetSource() string {
	if o == nil || IsNil(o.Source) {
		var ret string
		return ret
	}
	return *o.Source
}

// GetSourceOk returns a tuple with the Source field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SlurmdbV0041DeleteSingleQos200ResponseErrorsInner) GetSourceOk() (*string, bool) {
	if o == nil || IsNil(o.Source) {
		return nil, false
	}
	return o.Source, true
}

// HasSource returns a boolean if a field has been set.
func (o *SlurmdbV0041DeleteSingleQos200ResponseErrorsInner) HasSource() bool {
	if o != nil && !IsNil(o.Source) {
		return true
	}

	return false
}

// SetSource gets a reference to the given string and assigns it to the Source field.
func (o *SlurmdbV0041DeleteSingleQos200ResponseErrorsInner) SetSource(v string) {
	o.Source = &v
}

func (o SlurmdbV0041DeleteSingleQos200ResponseErrorsInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SlurmdbV0041DeleteSingleQos200ResponseErrorsInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	if !IsNil(o.ErrorNumber) {
		toSerialize["error_number"] = o.ErrorNumber
	}
	if !IsNil(o.Error) {
		toSerialize["error"] = o.Error
	}
	if !IsNil(o.Source) {
		toSerialize["source"] = o.Source
	}
	return toSerialize, nil
}

type NullableSlurmdbV0041DeleteSingleQos200ResponseErrorsInner struct {
	value *SlurmdbV0041DeleteSingleQos200ResponseErrorsInner
	isSet bool
}

func (v NullableSlurmdbV0041DeleteSingleQos200ResponseErrorsInner) Get() *SlurmdbV0041DeleteSingleQos200ResponseErrorsInner {
	return v.value
}

func (v *NullableSlurmdbV0041DeleteSingleQos200ResponseErrorsInner) Set(val *SlurmdbV0041DeleteSingleQos200ResponseErrorsInner) {
	v.value = val
	v.isSet = true
}

func (v NullableSlurmdbV0041DeleteSingleQos200ResponseErrorsInner) IsSet() bool {
	return v.isSet
}

func (v *NullableSlurmdbV0041DeleteSingleQos200ResponseErrorsInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSlurmdbV0041DeleteSingleQos200ResponseErrorsInner(val *SlurmdbV0041DeleteSingleQos200ResponseErrorsInner) *NullableSlurmdbV0041DeleteSingleQos200ResponseErrorsInner {
	return &NullableSlurmdbV0041DeleteSingleQos200ResponseErrorsInner{value: val, isSet: true}
}

func (v NullableSlurmdbV0041DeleteSingleQos200ResponseErrorsInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSlurmdbV0041DeleteSingleQos200ResponseErrorsInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


