/*
Slurm REST API

API to access and control Slurm

API version: Slurm-24.05.3&openapi/slurmdbd&openapi/slurmctld
Contact: sales@schedmd.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the V0041OpenapiPartitionResp type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &V0041OpenapiPartitionResp{}

// V0041OpenapiPartitionResp struct for V0041OpenapiPartitionResp
type V0041OpenapiPartitionResp struct {
	// List of partitions
	Partitions []V0041OpenapiPartitionRespPartitionsInner `json:"partitions"`
	LastUpdate V0041OpenapiPartitionRespLastUpdate `json:"last_update"`
	Meta *SlurmdbV0041DeleteSingleQos200ResponseMeta `json:"meta,omitempty"`
	// Query errors
	Errors []SlurmdbV0041DeleteSingleQos200ResponseErrorsInner `json:"errors,omitempty"`
	// Query warnings
	Warnings []SlurmdbV0041DeleteSingleQos200ResponseWarningsInner `json:"warnings,omitempty"`
}

type _V0041OpenapiPartitionResp V0041OpenapiPartitionResp

// NewV0041OpenapiPartitionResp instantiates a new V0041OpenapiPartitionResp object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewV0041OpenapiPartitionResp(partitions []V0041OpenapiPartitionRespPartitionsInner, lastUpdate V0041OpenapiPartitionRespLastUpdate) *V0041OpenapiPartitionResp {
	this := V0041OpenapiPartitionResp{}
	this.Partitions = partitions
	this.LastUpdate = lastUpdate
	return &this
}

// NewV0041OpenapiPartitionRespWithDefaults instantiates a new V0041OpenapiPartitionResp object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewV0041OpenapiPartitionRespWithDefaults() *V0041OpenapiPartitionResp {
	this := V0041OpenapiPartitionResp{}
	return &this
}

// GetPartitions returns the Partitions field value
func (o *V0041OpenapiPartitionResp) GetPartitions() []V0041OpenapiPartitionRespPartitionsInner {
	if o == nil {
		var ret []V0041OpenapiPartitionRespPartitionsInner
		return ret
	}

	return o.Partitions
}

// GetPartitionsOk returns a tuple with the Partitions field value
// and a boolean to check if the value has been set.
func (o *V0041OpenapiPartitionResp) GetPartitionsOk() ([]V0041OpenapiPartitionRespPartitionsInner, bool) {
	if o == nil {
		return nil, false
	}
	return o.Partitions, true
}

// SetPartitions sets field value
func (o *V0041OpenapiPartitionResp) SetPartitions(v []V0041OpenapiPartitionRespPartitionsInner) {
	o.Partitions = v
}

// GetLastUpdate returns the LastUpdate field value
func (o *V0041OpenapiPartitionResp) GetLastUpdate() V0041OpenapiPartitionRespLastUpdate {
	if o == nil {
		var ret V0041OpenapiPartitionRespLastUpdate
		return ret
	}

	return o.LastUpdate
}

// GetLastUpdateOk returns a tuple with the LastUpdate field value
// and a boolean to check if the value has been set.
func (o *V0041OpenapiPartitionResp) GetLastUpdateOk() (*V0041OpenapiPartitionRespLastUpdate, bool) {
	if o == nil {
		return nil, false
	}
	return &o.LastUpdate, true
}

// SetLastUpdate sets field value
func (o *V0041OpenapiPartitionResp) SetLastUpdate(v V0041OpenapiPartitionRespLastUpdate) {
	o.LastUpdate = v
}

// GetMeta returns the Meta field value if set, zero value otherwise.
func (o *V0041OpenapiPartitionResp) GetMeta() SlurmdbV0041DeleteSingleQos200ResponseMeta {
	if o == nil || IsNil(o.Meta) {
		var ret SlurmdbV0041DeleteSingleQos200ResponseMeta
		return ret
	}
	return *o.Meta
}

// GetMetaOk returns a tuple with the Meta field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V0041OpenapiPartitionResp) GetMetaOk() (*SlurmdbV0041DeleteSingleQos200ResponseMeta, bool) {
	if o == nil || IsNil(o.Meta) {
		return nil, false
	}
	return o.Meta, true
}

// HasMeta returns a boolean if a field has been set.
func (o *V0041OpenapiPartitionResp) HasMeta() bool {
	if o != nil && !IsNil(o.Meta) {
		return true
	}

	return false
}

// SetMeta gets a reference to the given SlurmdbV0041DeleteSingleQos200ResponseMeta and assigns it to the Meta field.
func (o *V0041OpenapiPartitionResp) SetMeta(v SlurmdbV0041DeleteSingleQos200ResponseMeta) {
	o.Meta = &v
}

// GetErrors returns the Errors field value if set, zero value otherwise.
func (o *V0041OpenapiPartitionResp) GetErrors() []SlurmdbV0041DeleteSingleQos200ResponseErrorsInner {
	if o == nil || IsNil(o.Errors) {
		var ret []SlurmdbV0041DeleteSingleQos200ResponseErrorsInner
		return ret
	}
	return o.Errors
}

// GetErrorsOk returns a tuple with the Errors field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V0041OpenapiPartitionResp) GetErrorsOk() ([]SlurmdbV0041DeleteSingleQos200ResponseErrorsInner, bool) {
	if o == nil || IsNil(o.Errors) {
		return nil, false
	}
	return o.Errors, true
}

// HasErrors returns a boolean if a field has been set.
func (o *V0041OpenapiPartitionResp) HasErrors() bool {
	if o != nil && !IsNil(o.Errors) {
		return true
	}

	return false
}

// SetErrors gets a reference to the given []SlurmdbV0041DeleteSingleQos200ResponseErrorsInner and assigns it to the Errors field.
func (o *V0041OpenapiPartitionResp) SetErrors(v []SlurmdbV0041DeleteSingleQos200ResponseErrorsInner) {
	o.Errors = v
}

// GetWarnings returns the Warnings field value if set, zero value otherwise.
func (o *V0041OpenapiPartitionResp) GetWarnings() []SlurmdbV0041DeleteSingleQos200ResponseWarningsInner {
	if o == nil || IsNil(o.Warnings) {
		var ret []SlurmdbV0041DeleteSingleQos200ResponseWarningsInner
		return ret
	}
	return o.Warnings
}

// GetWarningsOk returns a tuple with the Warnings field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V0041OpenapiPartitionResp) GetWarningsOk() ([]SlurmdbV0041DeleteSingleQos200ResponseWarningsInner, bool) {
	if o == nil || IsNil(o.Warnings) {
		return nil, false
	}
	return o.Warnings, true
}

// HasWarnings returns a boolean if a field has been set.
func (o *V0041OpenapiPartitionResp) HasWarnings() bool {
	if o != nil && !IsNil(o.Warnings) {
		return true
	}

	return false
}

// SetWarnings gets a reference to the given []SlurmdbV0041DeleteSingleQos200ResponseWarningsInner and assigns it to the Warnings field.
func (o *V0041OpenapiPartitionResp) SetWarnings(v []SlurmdbV0041DeleteSingleQos200ResponseWarningsInner) {
	o.Warnings = v
}

func (o V0041OpenapiPartitionResp) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o V0041OpenapiPartitionResp) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["partitions"] = o.Partitions
	toSerialize["last_update"] = o.LastUpdate
	if !IsNil(o.Meta) {
		toSerialize["meta"] = o.Meta
	}
	if !IsNil(o.Errors) {
		toSerialize["errors"] = o.Errors
	}
	if !IsNil(o.Warnings) {
		toSerialize["warnings"] = o.Warnings
	}
	return toSerialize, nil
}

func (o *V0041OpenapiPartitionResp) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"partitions",
		"last_update",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varV0041OpenapiPartitionResp := _V0041OpenapiPartitionResp{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varV0041OpenapiPartitionResp)

	if err != nil {
		return err
	}

	*o = V0041OpenapiPartitionResp(varV0041OpenapiPartitionResp)

	return err
}

type NullableV0041OpenapiPartitionResp struct {
	value *V0041OpenapiPartitionResp
	isSet bool
}

func (v NullableV0041OpenapiPartitionResp) Get() *V0041OpenapiPartitionResp {
	return v.value
}

func (v *NullableV0041OpenapiPartitionResp) Set(val *V0041OpenapiPartitionResp) {
	v.value = val
	v.isSet = true
}

func (v NullableV0041OpenapiPartitionResp) IsSet() bool {
	return v.isSet
}

func (v *NullableV0041OpenapiPartitionResp) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableV0041OpenapiPartitionResp(val *V0041OpenapiPartitionResp) *NullableV0041OpenapiPartitionResp {
	return &NullableV0041OpenapiPartitionResp{value: val, isSet: true}
}

func (v NullableV0041OpenapiPartitionResp) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableV0041OpenapiPartitionResp) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


