/*
Slurm REST API

API to access and control Slurm

API version: Slurm-24.05.3&openapi/slurmdbd&openapi/slurmctld
Contact: sales@schedmd.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi_slurm_24_05

import (
	"encoding/json"
)

// checks if the SlurmdbV0041DeleteSingleQos200ResponseMetaSlurm type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SlurmdbV0041DeleteSingleQos200ResponseMetaSlurm{}

// SlurmdbV0041DeleteSingleQos200ResponseMetaSlurm struct for SlurmdbV0041DeleteSingleQos200ResponseMetaSlurm
type SlurmdbV0041DeleteSingleQos200ResponseMetaSlurm struct {
	Version *SlurmdbV0041DeleteSingleQos200ResponseMetaSlurmVersion `json:"version,omitempty"`
	// Slurm release string
	Release *string `json:"release,omitempty"`
	// Slurm cluster name
	Cluster *string `json:"cluster,omitempty"`
}

// NewSlurmdbV0041DeleteSingleQos200ResponseMetaSlurm instantiates a new SlurmdbV0041DeleteSingleQos200ResponseMetaSlurm object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSlurmdbV0041DeleteSingleQos200ResponseMetaSlurm() *SlurmdbV0041DeleteSingleQos200ResponseMetaSlurm {
	this := SlurmdbV0041DeleteSingleQos200ResponseMetaSlurm{}
	return &this
}

// NewSlurmdbV0041DeleteSingleQos200ResponseMetaSlurmWithDefaults instantiates a new SlurmdbV0041DeleteSingleQos200ResponseMetaSlurm object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSlurmdbV0041DeleteSingleQos200ResponseMetaSlurmWithDefaults() *SlurmdbV0041DeleteSingleQos200ResponseMetaSlurm {
	this := SlurmdbV0041DeleteSingleQos200ResponseMetaSlurm{}
	return &this
}

// GetVersion returns the Version field value if set, zero value otherwise.
func (o *SlurmdbV0041DeleteSingleQos200ResponseMetaSlurm) GetVersion() SlurmdbV0041DeleteSingleQos200ResponseMetaSlurmVersion {
	if o == nil || IsNil(o.Version) {
		var ret SlurmdbV0041DeleteSingleQos200ResponseMetaSlurmVersion
		return ret
	}
	return *o.Version
}

// GetVersionOk returns a tuple with the Version field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SlurmdbV0041DeleteSingleQos200ResponseMetaSlurm) GetVersionOk() (*SlurmdbV0041DeleteSingleQos200ResponseMetaSlurmVersion, bool) {
	if o == nil || IsNil(o.Version) {
		return nil, false
	}
	return o.Version, true
}

// HasVersion returns a boolean if a field has been set.
func (o *SlurmdbV0041DeleteSingleQos200ResponseMetaSlurm) HasVersion() bool {
	if o != nil && !IsNil(o.Version) {
		return true
	}

	return false
}

// SetVersion gets a reference to the given SlurmdbV0041DeleteSingleQos200ResponseMetaSlurmVersion and assigns it to the Version field.
func (o *SlurmdbV0041DeleteSingleQos200ResponseMetaSlurm) SetVersion(v SlurmdbV0041DeleteSingleQos200ResponseMetaSlurmVersion) {
	o.Version = &v
}

// GetRelease returns the Release field value if set, zero value otherwise.
func (o *SlurmdbV0041DeleteSingleQos200ResponseMetaSlurm) GetRelease() string {
	if o == nil || IsNil(o.Release) {
		var ret string
		return ret
	}
	return *o.Release
}

// GetReleaseOk returns a tuple with the Release field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SlurmdbV0041DeleteSingleQos200ResponseMetaSlurm) GetReleaseOk() (*string, bool) {
	if o == nil || IsNil(o.Release) {
		return nil, false
	}
	return o.Release, true
}

// HasRelease returns a boolean if a field has been set.
func (o *SlurmdbV0041DeleteSingleQos200ResponseMetaSlurm) HasRelease() bool {
	if o != nil && !IsNil(o.Release) {
		return true
	}

	return false
}

// SetRelease gets a reference to the given string and assigns it to the Release field.
func (o *SlurmdbV0041DeleteSingleQos200ResponseMetaSlurm) SetRelease(v string) {
	o.Release = &v
}

// GetCluster returns the Cluster field value if set, zero value otherwise.
func (o *SlurmdbV0041DeleteSingleQos200ResponseMetaSlurm) GetCluster() string {
	if o == nil || IsNil(o.Cluster) {
		var ret string
		return ret
	}
	return *o.Cluster
}

// GetClusterOk returns a tuple with the Cluster field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SlurmdbV0041DeleteSingleQos200ResponseMetaSlurm) GetClusterOk() (*string, bool) {
	if o == nil || IsNil(o.Cluster) {
		return nil, false
	}
	return o.Cluster, true
}

// HasCluster returns a boolean if a field has been set.
func (o *SlurmdbV0041DeleteSingleQos200ResponseMetaSlurm) HasCluster() bool {
	if o != nil && !IsNil(o.Cluster) {
		return true
	}

	return false
}

// SetCluster gets a reference to the given string and assigns it to the Cluster field.
func (o *SlurmdbV0041DeleteSingleQos200ResponseMetaSlurm) SetCluster(v string) {
	o.Cluster = &v
}

func (o SlurmdbV0041DeleteSingleQos200ResponseMetaSlurm) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SlurmdbV0041DeleteSingleQos200ResponseMetaSlurm) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Version) {
		toSerialize["version"] = o.Version
	}
	if !IsNil(o.Release) {
		toSerialize["release"] = o.Release
	}
	if !IsNil(o.Cluster) {
		toSerialize["cluster"] = o.Cluster
	}
	return toSerialize, nil
}

type NullableSlurmdbV0041DeleteSingleQos200ResponseMetaSlurm struct {
	value *SlurmdbV0041DeleteSingleQos200ResponseMetaSlurm
	isSet bool
}

func (v NullableSlurmdbV0041DeleteSingleQos200ResponseMetaSlurm) Get() *SlurmdbV0041DeleteSingleQos200ResponseMetaSlurm {
	return v.value
}

func (v *NullableSlurmdbV0041DeleteSingleQos200ResponseMetaSlurm) Set(val *SlurmdbV0041DeleteSingleQos200ResponseMetaSlurm) {
	v.value = val
	v.isSet = true
}

func (v NullableSlurmdbV0041DeleteSingleQos200ResponseMetaSlurm) IsSet() bool {
	return v.isSet
}

func (v *NullableSlurmdbV0041DeleteSingleQos200ResponseMetaSlurm) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSlurmdbV0041DeleteSingleQos200ResponseMetaSlurm(val *SlurmdbV0041DeleteSingleQos200ResponseMetaSlurm) *NullableSlurmdbV0041DeleteSingleQos200ResponseMetaSlurm {
	return &NullableSlurmdbV0041DeleteSingleQos200ResponseMetaSlurm{value: val, isSet: true}
}

func (v NullableSlurmdbV0041DeleteSingleQos200ResponseMetaSlurm) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSlurmdbV0041DeleteSingleQos200ResponseMetaSlurm) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


